apply plugin: 'com.android.application'

def AAVersion = '4.8.0'

dependencies {
    implementation project(':drag-sort-listview-gradle')
    implementation 'commons-io:commons-io:2.4'
    implementation 'org.apache.commons:commons-lang3:3.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.6.1'
    implementation 'org.mobilitydata:gtfs-realtime-bindings:0.0.8'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'io.sentry:sentry-android:1.7.14'
    implementation 'org.slf4j:slf4j-nop:1.7.25'

    implementation 'androidx.core:core:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'

    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    implementation "org.androidannotations:androidannotations-api:$AAVersion"
}

android {
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        versionName "2.2.21"
        versionCode 56

        minSdkVersion 21
        targetSdkVersion 36

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                        androidManifestFile: file("$projectDir/src/main/AndroidManifest.xml").absolutePath,
                        resourcePackageName: "com.dougkeen.bart"
                ]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/license.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt', 'META-INF/notice.txt']
        }
    }

    ndkVersion '25.1.8937393'
    namespace 'com.dougkeen.bart'
    lint {
        abortOnError false
    }
}
