apply plugin: 'com.android.library'

// This file is here (rather than in the drag-sort-listview project)
// so we can control how it builds without having to submit pull requests.

dependencies {
    implementation 'androidx.cursoradapter:cursoradapter:1.0.0'
}

android {
    namespace 'com.mobeta.android.dslv'
    compileSdkVersion 36

    defaultConfig {
        targetSdkVersion 36
        minSdkVersion 21
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    sourceSets {
        main {
            manifest.srcFile '../drag-sort-listview/library/AndroidManifest.xml'
            java.srcDirs = ['../drag-sort-listview/library/src']
            res.srcDirs = ['../drag-sort-listview/library/res']
        }
    }
    lint {
        abortOnError false
    }

}

